### ISSUE TITLE
No module named 'axolotl.kdf'

### ISSUE THREAD

**Issue by DiyRex** [open-wa/wa-automate-python#71]
Axolotl coming soon!
Traceback (most recent call last):
  File "C:\Users\Devin\PycharmProjects\pythonProject2\Wa-Bot\wabot.py", line 1, in <module>
    from openwa import WhatsAPIDriver
  File "C:\Users\Devin\AppData\Local\Programs\Python\Python39\lib\site-packages\openwa\__init__.py", line 20, in <module>
    from axolotl.kdf.hkdfv3 import HKDFv3
ModuleNotFoundError: No module named 'axolotl.kdf'

I tried pip install -r requirements.txt but I get this error

**Comment by mrodal** [comment]
Hi, please check https://github.com/open-wa/wa-automate-python/issues/3
