### ISSUE TITLE
How do I add the geckodriver path on linux environment ?

### ISSUE THREAD

**Issue by TheCuddleDoodle** [open-wa/wa-automate-python#72]
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 2, in <module>
    driver = WhatsAPIDriver()
  File "/usr/local/lib/python3.7/dist-packages/openwa/__init__.py", line 195, in __init__
    **extra_params)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

**Comment by mrodal** [comment]
Hi, this is a linux question, please google "'geckodriver' executable needs to be in PATH"

**Comment by TheCuddleDoodle** [comment]
copying geckodriver to 
 ```/usr/local/bin```
seems to be working.
